version: '3'

services:

  client:

    build:
      context: './client'
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    container_name: client-container

    networks:
        - social-media-network

    volumes:
      - ./client:/app/

    depends_on:
      - server

  server:

    build:
      context: './server'
      dockerfile: Dockerfile

    ports:
      - '5000:5000'

    container_name: server-container

    networks:
        - social-media-network

    volumes:
      - ./server:/app/

#    depends_on:
#      - database

#  database:
#
#    image: mongo
#
#    ports:
#      - '27017:27017'
#
#    container_name: db-container
#
#    networks:
#        - social-media-network
#
#    volumes:
#      - database-data:/data/db
#
#    restart: always
#
#    environment:
#      MONGO_INITDB_ROOT_USERNAME:
#      MONGO_INITDB_ROOT_PASSWORD:


